// Generated by CoffeeScript 1.4.0
var Emblem;

this.Emblem = {};

Emblem = this.Emblem;

module.exports = Emblem;

require('handlebars');

require('./parser');

require('./compiler');

require('./preprocessor');

require('./translation');

require('./emberties');
