// Generated by CoffeeScript 1.4.0
"BEGIN BROWSER";

var Emblem;

this.Emblem = {};

Emblem = this.Emblem;

"END BROWSER";


module.exports = Emblem;

require('handlebars');

require('./parser');

require('./compiler');

require('./preprocessor');

require('./translation');

require('./emberties');
