// Generated by CoffeeScript 1.3.3
var Preprocessor, fs;

Preprocessor = require('preprocessor').Preprocessor;

fs = require('fs');

console.log(Preprocessor.processSync(fs.readFileSync('test.emblem')));
