export default {
  figcaption: true, blockquote: true, plaintext: true, textarea: true, progress: true,
  optgroup: true, noscript: true, noframes: true, frameset: true, fieldset: true,
  datalist: true, colgroup: true, basefont: true, summary: true, section: true,
  marquee: true, listing: true, isindex: true, details: true, command: true,
  caption: true, bgsound: true, article: true, address: true, acronym: true,
  strong: true, strike: true, spacer: true, source: true, select: true,
  script: true, output: true, option: true, object: true, legend: true,
  keygen: true, iframe: true, hgroup: true, header: true, footer: true,
  figure: true, center: true, canvas: true, button: true, applet: true, video: true,
  track: true, title: true, thead: true, tfoot: true, tbody: true, table: true,
  style: true, small: true, param: true, meter: true, label: true, input: true,
  frame: true, embed: true, blink: true, audio: true, aside: true, time: true,
  span: true, samp: true, ruby: true, nobr: true, meta: true, menu: true,
  mark: true, main: true, link: true, html: true, head: true, form: true,
  font: true, data: true, code: true, cite: true, body: true, base: true,
  area: true, abbr: true, xmp: true, wbr: true, 'var': true, sup: true,
  sub: true, pre: true, nav: true, map: true, kbd: true, ins: true,
  img: true, div: true, dir: true, dfn: true, del: true, col: true,
  big: true, bdo: true, bdi: true, ul: true, tt: true, tr: true, th: true, td: true,
  rt: true, rp: true, ol: true, li: true, hr: true, h6: true, h5: true, h4: true,
  h3: true, h2: true, h1: true, em: true, dt: true, dl: true, dd: true, br: true,
  u: true, s: true, q: true, p: true, i: true, b: true, a: true
};
